version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: efdb-backend-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: "pg_isready -U $DB_USER -d $DB_NAME"
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  db-data:
